import React from 'react';
import { 
  Brain, 
  Target, 
  ShieldCheck, 
  TrendingUp, 
  Network, 
  LineChart, 
  Eye, 
  Award, 
  Zap, 
  Infinity 
} from 'lucide-react';
import { Equation } from './types';

export const EQUATIONS: Equation[] = [
  {
    id: 'bayesian',
    number: '01',
    title: '確信度アップデート',
    subtitle: '判断：思い込みを科学的に修正する',
    formula: 'P(A|B) = \\frac{P(B|A)P(A)}{P(B)}',
    description: '新しい証拠を見て、自分の「自信」を正しく書き換える。直感のミスを防ぐ最強の武器。',
    icon: <Brain className="w-8 h-8" />,
    isAvailable: true,
  },
  {
    id: 'logistic',
    number: '02',
    title: '勝ち馬診断機',
    subtitle: '賭け：破産せずにお金を増やす黄金比',
    formula: 'f^* = \\frac{bp-q}{b}',
    description: '「いくら突っ込むべきか？」の答えを出す。期待値から逆算して、リスクを最小に、利益を最大にする。',
    icon: <Target className="w-8 h-8" />,
    isAvailable: true,
  },
  {
    id: 'confidence',
    number: '03',
    title: 'たまたまじゃない度',
    subtitle: '信頼：そのデータ、嘘か真実か？',
    formula: '\\hat{p} \\pm 1.96 \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}',
    description: 'たった数人の意見を信じていいのか？ 誤差の範囲を見極め、騙されない目を持つ。',
    icon: <ShieldCheck className="w-8 h-8" />,
    isAvailable: true,
  },
  {
    id: 'markov',
    number: '04',
    title: '将来の幸福配分',
    subtitle: 'スキル：今の好調がいつまで続くか？',
    formula: 'P(X_{n+1} = j | X_n = i) = p_{ij}',
    description: '好不調の波を数値化し、長期的に自分がどれくらい「幸せな状態」にいられるかを予測する。',
    icon: <TrendingUp className="w-8 h-8" />,
    isAvailable: true,
  },
  {
    id: 'pagerank',
    number: '05',
    title: '影の支配者チェッカー',
    subtitle: '影響力：誰が「本当のパワー」を持っているか？',
    formula: 'PR(u) = \\frac{1-d}{N} + d \\sum \\frac{PR(v)}{L(v)}',
    description: '単に有名な人ではなく、重要な人とつながっている人を探す。組織を裏で操る「ハブ」を特定する。',
    icon: <Network className="w-8 h-8" />,
    isAvailable: true,
  },
  {
    id: 'market',
    number: '06',
    title: 'パニック・チェッカー',
    subtitle: '市場：熱狂か、恐怖か？',
    formula: '\\sigma = \\sqrt{\\frac{1}{N-1} \\sum (x_i - \\mu)^2}',
    description: '市場の「ボラティリティ」から、大衆がパニックに陥っているか、浮かれているかを算出する。',
    icon: <LineChart className="w-8 h-8" />,
    isAvailable: true,
  },
  {
    id: 'correlation',
    number: '07',
    title: '欲望プロファイラー',
    subtitle: '広告：あなたの「欲しい」は暴かれている',
    formula: 'r = \\frac{Cov(X,Y)}{\\sigma_X \\sigma_Y}',
    description: '無関係に見える行動の繋がりから、あなたの本音を炙り出す。予測され、操られる恐怖を知る。',
    icon: <Eye className="w-8 h-8" />,
    isAvailable: true,
  },
  {
    id: 'qlearning',
    number: '08',
    title: '人生の攻略レシピ',
    subtitle: '報酬：未知への挑戦か、今の安定か',
    formula: 'Q(s,a) \\leftarrow Q(s,a) + \\alpha(r + \\gamma \\max Q - Q)',
    description: 'いつまでも同じことを続けるべきか、新しい道を行くべきか。AIが使う最適解を導く。',
    icon: <Award className="w-8 h-8" />,
    isAvailable: true,
  },
  {
    id: 'gradient',
    number: '09',
    title: '最短ルート見極め術',
    subtitle: '学習：挫折せず「正解」へ辿り着く',
    formula: '\\theta_{t+1} = \\theta_t - \\eta \\nabla J',
    description: '無駄な努力を捨て、エラー（失敗）を最小化する。最も効率的に目標を達成する「歩幅」を知る。',
    icon: <Zap className="w-8 h-8" />,
    isAvailable: true,
  },
  {
    id: 'ifthen',
    number: '10',
    title: '感情排除プログラム',
    subtitle: '普遍：悩みから「人間らしさ」を消す',
    formula: 'P \\implies Q',
    description: 'グチャグチャな悩みを「もし〜なら」のコードに変換。迷いを消し、マシンのように決断する。',
    icon: <Infinity className="w-8 h-8" />,
    isAvailable: true,
  },
];